_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
smtp_on: true
smtp_host: email-smtp.us-east-1.amazonaws.com
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: test
smtp_password: test
smtp_from: do-not-reply@submit.diginole.lib.fsu.edu
smtp_fromname: submit.diginole
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
